language: elixir

matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8.2
    - otp_release: 21.3
      elixir: 1.9.2

    - otp_release: 22.1
      elixir: 1.8.2
    - otp_release: 22.1
      elixir: 1.9.2

sudo: false

before_script:
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
